# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MessageNamespace

class Contents(object):
    NONE = 0
    ResponseContents = 1
    HealthContents = 2
    OrderContents = 3
