# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PA

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Cans(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Cans()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCans(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Cans
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Cans
    def Coke(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Cans
    def Beer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Cans
    def Pepsi(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def CansStart(builder):
    builder.StartObject(3)

def Start(builder):
    CansStart(builder)

def CansAddCoke(builder, coke):
    builder.PrependInt32Slot(0, coke, 0)

def AddCoke(builder, coke):
    CansAddCoke(builder, coke)

def CansAddBeer(builder, beer):
    builder.PrependInt32Slot(1, beer, 0)

def AddBeer(builder, beer):
    CansAddBeer(builder, beer)

def CansAddPepsi(builder, pepsi):
    builder.PrependInt32Slot(2, pepsi, 0)

def AddPepsi(builder, pepsi):
    CansAddPepsi(builder, pepsi)

def CansEnd(builder):
    return builder.EndObject()

def End(builder):
    return CansEnd(builder)
