# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\x17\n\x07Request\x12\x0c\n\x04type\x18\x01 \x01(\r\"8\n\x08Response\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0c\n\x04\x63ode\x18\x02 \x01(\r\x12\x10\n\x08\x63ontents\x18\x03 \x01(\t*2\n\x0bMessageType\x12\t\n\x05ORDER\x10\x00\x12\n\n\x06HEALTH\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x32/\n\x0c\x44ummyService\x12\x1f\n\x06method\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGETYPE']._serialized_start=99
  _globals['_MESSAGETYPE']._serialized_end=149
  _globals['_REQUEST']._serialized_start=16
  _globals['_REQUEST']._serialized_end=39
  _globals['_RESPONSE']._serialized_start=41
  _globals['_RESPONSE']._serialized_end=97
  _globals['_DUMMYSERVICE']._serialized_start=151
  _globals['_DUMMYSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
