# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PA

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HealthContents(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HealthContents()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHealthContents(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HealthContents
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HealthContents
    def Contents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HealthContentsStart(builder):
    builder.StartObject(1)

def Start(builder):
    HealthContentsStart(builder)

def HealthContentsAddContents(builder, contents):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(contents), 0)

def AddContents(builder, contents):
    HealthContentsAddContents(builder, contents)

def HealthContentsEnd(builder):
    return builder.EndObject()

def End(builder):
    return HealthContentsEnd(builder)
