# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PA

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OrderContents(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OrderContents()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOrderContents(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OrderContents
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OrderContents
    def Veggies(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from PA.Veggies import Veggies
            obj = Veggies()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderContents
    def Drinks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from PA.Drinks import Drinks
            obj = Drinks()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def OrderContentsStart(builder):
    builder.StartObject(2)

def Start(builder):
    OrderContentsStart(builder)

def OrderContentsAddVeggies(builder, veggies):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(veggies), 0)

def AddVeggies(builder, veggies):
    OrderContentsAddVeggies(builder, veggies)

def OrderContentsAddDrinks(builder, drinks):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(drinks), 0)

def AddDrinks(builder, drinks):
    OrderContentsAddDrinks(builder, drinks)

def OrderContentsEnd(builder):
    return builder.EndObject()

def End(builder):
    return OrderContentsEnd(builder)
